### ISSUE TITLE
1주차 마무리 및 다음회차 결정해봐요~

### ISSUE THREAD

**Issue by jiji-hoon96** [code-bibliotheca/clean-code#1]
1. 다음 주 서기는 누구할지!
2. 다음 주 스터디는 오전 9시로 할려고하는데 괜찮을까요?
3. 스터디 장소는 누가 정할가요!

**Comment by jiji-hoon96** [comment]
1. 다음은 팀장님이 해보시는것도!
2. 제가 의견내서... 부탁드릴게여!! ㅠㅠ!!
3. 부탁드릴게요 @bubobubobo  zz!!!

**Comment by bubobubobo** [comment]
ㅋㅋㅋㅋ
1. 제가 하겠습니다.
2. 맞다 유정님께 말씀 안드렸다...
3. 넹 되는대로 내일 예약하고 말씀 드리겠습니다.

**Comment by jiji-hoon96** [comment]
마지막 댓글다는사람이 확인후에 issue 종료해주세요~~!!!
